name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.102'
      
      - name: Build with MSBuild
        run: msbuild /t:Restore, Build /p:Configuration=Release

      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --configuration Release

      - name: Install Roslynator Analyzers
        run: dotnet tool install --global Roslynator.Analyzers
      
      - name: Run code analysis
        run: dotnet roslynator analyze --solution-directory ./ --formatter-json-file ./roslynator.json
        
      - name: Upload code analysis report
        uses: actions/upload-artifact@v2
        with:
          name: code-analysis-report
          path: ./roslynator.json
      
      - name: Run tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish artifatc
        run: dotnet publish -c Release -o ./publish
        
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: published-artiface
          path: ./publish
