name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy: 
      fail-fast: false
      matrix:
        projectPath:
          -  ${{ github.workspace }}
        testMode:
          - playmode
          - editmode
          - standalone

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
    
      - name: Return license
        uses: game-ci/unity-return-license@v2
        if: always()

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: Library
          key: ${{ runner.os }}-unity-${{ hashFiles('**/ProjectSettings/ProjectVersion.txt') }}
          
      - name: Test runner
        uses: game-ci/unity-test-runner@v4
        with:
          path: ${{ github.workspace }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          packageMode: false
          unityVersion: 2022.3.17f1

      - uses: game-ci/unity-test-runner@v4
        id: gameTestStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport;assemblyFilters:+my.assembly.*'

      - name: Check code style
        uses: hachque/run-stylecop-action@v1
        with:
          path: './Assets'

      - name: Build project
        run: |
          ./Unity/Editor/Unity -quit -batchmode -projectPath . -buildTarget StandaloneWindows64 -buildPath build
          mkdir -p artifacts
          mv build/*.exe artifacts/
        
      - name: Build repository
        uses: game-ci/unity-builder@v4

      
        with:
          targetPlatform: WebGL
